# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.15"
  amd64: "ghcr.io/home-assistant/amd64-base:3.15"
  # armhf: "ghcr.io/home-assistant/armhf-base:3.15"
  # armv7: "ghcr.io/home-assistant/armv7-base:3.15"
  # i386: "ghcr.io/home-assistant/i386-base:3.15"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: ntfy"
  org.opencontainers.image.description: "Send push notifications to your phone or desktop using PUT/POST"
  org.opencontainers.image.source: "https://github.com/mikesplain/ha-addon-ntfy"
  org.opencontainers.image.licenses: "Apache License 2.0"
args:
  NTFY_VERSION: "v2.11.0"
