# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: ntfy
version: "2.11.0"
slug: ntfy
description: ntfy for hassio
url: "https://github.com/mikesplain/ha-addon-ntfy/tree/main/ntfy"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
# ingress: true
# ingress_port: 80
# ingress_stream: true
# ingress_entry: "/"
webui: "[PROTO:ssl]://[HOST]:[PORT:7612]"
ports:
  7612/tcp: 7612
  7612/udp: 7612
ports_description:
  80/tcp: ntfy ui/api tcp
  80/udp: ntfy ui/api udp
  443/tcp: ntfy tls ui/api tcp
  443/udp: ntfy tls ui/api udp
map:
  - ssl
# environment:
#   NTFY_BASE_URL: http://localhost:7123/hassio/ingress/local_ntfy
options:
  ssl: true
  certfile: fullchain.pem
  keyfile: privkey.pem
  base_url: ntfy.example.com
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  ssl: bool
  certfile: str
  keyfile: str
  base_url: str
# image: "ghcr.io/mikesplain/{arch}-ha-addon-ntfy"
