# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: ntfy
version: "2.11.0"
slug: ntfy
description: ntfy for hassio
url: "github.com/mikesplain/ha-addon-ntfy/tree/main/example"
arch:
  # - armhf
  # - armv7
  - aarch64
  - amd64
  # - i386
init: false
map:
  - share:rw
options:
  message: "Hello world..."
schema:
  message: "str?"
image: "ghcr.io/mikesplain/ha-addon-ntfy"
