# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: ntfy
version: "2.11.0"
slug: ntfy
description: ntfy for hassio
url: "https://github.com/mikesplain/ha-addon-ntfy/tree/main/ntfy"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
ingress: true
ingress_port: 80
ingress_stream: true
# ingress_entry: "/"
webuil: "http://[HOST]:[PORT:80]"
ports:
  80/tcp: 8777
  80/udp: 8777
map:
  - homeassistant_config
  - share:rw
# environment:
#   NTFY_BASE_URL: http://localhost:7123/hassio/ingress/local_ntfy
options:
  message: "Hello world..."
schema:
  message: "str?"
# image: "ghcr.io/mikesplain/{arch}-ha-addon-ntfy"
